spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
#    hibernate:
##      ddl-auto: create-drop
#      show_sql: true
#      format_sql: true
  datasource:
    platform: postgres
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
flyway:
  enabled: true
  user: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  schemas: public
  url: ${POSTGRES_URL}